version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    container_name: clother_web
    command: gunicorn --bind 0.0.0.0:5000 run:app --workers 1 --threads 10 --worker-class eventlet --access-logfile '-'
    ports:
      - "5000:5000"
    volumes:
      - media_data:/usr/src/app/media
    env_file: ./web.dev.env
  db:
    image: postgres:latest
    container_name: clother_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./db.dev.env

volumes:
  media_data:
  postgres_data:
