"""Make foreign keys not nullable

Revision ID: 4e57a2f4ce02
Revises: 
Create Date: 2021-07-31 14:58:31.799294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e57a2f4ce02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'offer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('location', 'offer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'offer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('image', 'offer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
