"""Message now can be accociated only with one image

Revision ID: 50eeb37c2ccd
Revises: f452b5a31ed6
Create Date: 2021-04-11 02:05:57.416330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50eeb37c2ccd'
down_revision = 'f452b5a31ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'image')
    # ### end Alembic commands ###
