"""Add device token field to User

Revision ID: b58294802781
Revises: 50eeb37c2ccd
Create Date: 2021-04-16 03:38:20.017463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58294802781'
down_revision = '50eeb37c2ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('device_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'device_token')
    # ### end Alembic commands ###
